### ISSUE TITLE
Client SSL Handshake not synchonized

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#114]
We don't wait until we've finished handshaking the SSL connection before fireing the `connected()` event. This code was borrowed from Twisted and other similar code and is IHMO broken. We _have_ to wait until the SSL Handshake is complete (_somehow_) before firing the `connected()` event otherwise you end up with a race condition where you eventually break the socket.

prologic/kdb#4 needs this and I'm sure other projects would need this too for proper Client-side SSL.

See also related issue #53

**Comment by prologic** [comment]
Perhaps  [Tornado STARTTLS example](https://gist.github.com/weaver/293449) might be good to borrow code/inspiration from. See also related issue #113

**Comment by prologic** [comment]
I think #115 is kind of related to this and fixing this issue might also fix #115

**Comment by spaceone** [comment]
quick&dirty hotfix:
```
diff --git a/circuits/net/sockets.py b/circuits/net/sockets.py
index 1400968..b778fc6 100644
--- a/circuits/net/sockets.py
+++ b/circuits/net/sockets.py
@@ -273,11 +275,16 @@ class TCPClient(Client):
 
         self._poller.addReader(self, self._sock)
         if self.secure:
+            self._orgsock = self._sock
             self._sock = ssl_socket(
                 self._sock, self.keyfile, self.certfile,
                 do_handshake_on_connect=False
             )
-            _do_handshake_for_non_blocking(self._sock)
+            try:
+                _do_handshake_for_non_blocking(self._sock)
+            except SocketError as exc:
+                self._poller.discard(self._orgsock)
+                raise
 
         self.fire(connected(host, port))
 
```

**Comment by prologic** [comment]
Going to have a go at fixing this proper :)

**Comment by prologic** [comment]
Good news! Client SSL Handshake works!

**Example:**

```#!bash
(circuits)
prologic@daisy
Thu Aug 13 23:28:59 
~/circuits
$ python Issue#115.py 
<registered[client] (<TCPClient/client 23493:MainThread (queued=0) [S]>, <App/* 23493:MainThread (queued=3) [R]> )>
<registered[*] (<Debugger/* 23493:MainThread (queued=0) [S]>, <App/* 23493:MainThread (queued=4) [R]> )>
<started[*] (<App/* 23493:MainThread (queued=3) [R]> )>
<registered[select] (<Select/select 23493:MainThread (queued=0) [S]>, <TCPClient/client 23493:MainThread (queued=0) [S]> )>
<ready[client] (<TCPClient/client 23493:MainThread (queued=0) [S]> )>
<connect[*] ('www.google.com', 443, True )>
<connected[client] ('www.google.com', 443 )>
<write[*] ('GET / HTTP/1.1\r\nHost: www.google.com\r\nConnection: close\r\n\r\n' )>
<_write[client] (<ssl.SSLSocket object at 0x7fd6519f3de8> )>
<_read[client] (<ssl.SSLSocket object at 0x7fd6519f3de8> )>
<read[client] ('HTTP/1.1 302 Found\r\nCache-Control: private\r\nContent-Type: text/html; charset=UTF-8\r\nLocation: https://www.google.com.au/?gfe_rd=cr&ei=v5rMVbbmLbHu8we11IDYCg\r\nContent-Length: 263\r\nDate: Thu, 13 Aug 2015 13:25:19 GMT\r\nServer: GFE/2.0\r\nAlternate-Protocol: 443:quic,p=1\r\nAlt-Svc: quic=":443"; p="1"; ma=604800\r\nConnection: close\r\n\r\n<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">\n<TITLE>302 Moved</TITLE></HEAD><BODY>\n<H1>302 Moved</H1>\nThe document has moved\n<A HREF="https://www.google.com.au/?gfe_rd=cr&amp;ei=v5rMVbbmLbHu8we11IDYCg">here</A>.\r\n</BODY></HTML>\r\n' )>
HTTP/1.1 302 Found
Cache-Control: private
Content-Type: text/html; charset=UTF-8
Location: https://www.google.com.au/?gfe_rd=cr&ei=v5rMVbbmLbHu8we11IDYCg
Content-Length: 263
Date: Thu, 13 Aug 2015 13:25:19 GMT
Server: GFE/2.0
Alternate-Protocol: 443:quic,p=1
Alt-Svc: quic=":443"; p="1"; ma=604800
Connection: close

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://www.google.com.au/?gfe_rd=cr&amp;ei=v5rMVbbmLbHu8we11IDYCg">here</A>.
</BODY></HTML>

<_read[client] (<ssl.SSLSocket object at 0x7fd6519f3de8> )>
<disconnected[client] ( )>
```

**Comment by prologic** [comment]
@spaceone Good work on fixing Client SSL Handshake; your last PR was (*I believe*) the last piece to the puzzle which now allows prologic/kdb/#4 to work!

I still cannot get the unit test to work at all though :/

```#!bash
(circuits)
prologic@daisy
Sat Aug 22 19:20:38 
~/circuits
$ py.test -x -s -v -k test_tcps_basic tests/net/test_tcp.py 
======================================= test session starts ========================================
platform linux2 -- Python 2.7.10 -- py-1.4.28 -- pytest-2.7.1 -- /home/prologic/.virtualenvs/circuits/bin/python
rootdir: /home/prologic/work/circuits, inifile: 
plugins: cov
collected 36 items 

tests/net/test_tcp.py::test_tcps_basic[0] <registered[*] (<Debugger/* 29487:Manager (queued=0) [S]>, <Manager/ 29487:Manager (queued=7) [R]> )>
<registered[server] (<TCPServer/server 29487:Manager (queued=0) [S]>, <Server/server 29487:Manager (queued=0) [S]> )>
<registered[select] (<Select/select 29487:Manager (queued=0) [S]>, <Manager/ 29487:Manager (queued=6) [R]> )>
<registered[client] (<TCPClient/client 29487:Manager (queued=0) [S]>, <Client/client 29487:Manager (queued=0) [S]> )>
<registered[server] (<Server/server 29487:Manager (queued=0) [S]>, <Manager/ 29487:Manager (queued=5) [R]> )>
<registered[client] (<Client/client 29487:Manager (queued=0) [S]>, <Manager/ 29487:Manager (queued=4) [R]> )>
<started[*] (<Manager/ 29487:Manager (queued=3) [R]> )>
<ready[server] (<TCPServer/server 29487:Manager (queued=0) [S]>, ('10.0.0.2', 49599) )>
<ready[client] (<TCPClient/client 29487:Manager (queued=0) [S]> )>
<connect[client] ('10.0.0.2', 49599 secure=True)>
FAILED

============================================= FAILURES =============================================
________________________________________ test_tcps_basic[0] ________________________________________

Poller = <class 'circuits.core.pollers.Select'>, ipv6 = False

    def test_tcps_basic(Poller, ipv6):
        from circuits import Debugger
        m = Manager() + Debugger() + Poller()
    
        if ipv6:
            tcp_server = TCP6Server(("::1", 0), secure=True, certfile=CERT_FILE)
            tcp_client = TCP6Client()
        else:
            tcp_server = TCPServer(0, secure=True, certfile=CERT_FILE)
            tcp_client = TCPClient()
        server = Server() + tcp_server
        client = Client() + tcp_client
    
        server.register(m)
        client.register(m)
    
        m.start()
    
        try:
            assert pytest.wait_for(client, "ready")
            assert pytest.wait_for(server, "ready")
            wait_host(server)
    
            client.fire(connect(server.host, server.port, secure=True))
>           assert pytest.wait_for(client, "connected")
E           assert None
E            +  where None = <function wait_for at 0x7fe35cd87e60>(<Client/client 29487:MainThread (queued=0) [S]>, 'connected')
E            +    where <function wait_for at 0x7fe35cd87e60> = pytest.wait_for

tests/net/test_tcp.py:116: AssertionError
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================ 30 tests deselected by '-ktest_tcps_basic' ============================
============================= 1 failed, 30 deselected in 3.19 seconds ==============================
```

Any ideas?

**Comment by spaceone** [comment]
Previously to this changes I got the following exception. I hope this bug fixed it. I have no clue how to reproduce it:
```
ERROR <handler[*][_read][1.00] (TCPServer._on_read)> (<_read[http.server] (<socket._socketobject object at 0x9d45bfc> )>) (<type 'exceptions.AttributeError'>): AttributeError("'NoneType' object has no attribute 'do_handshake'",)
Traceback (most recent call last):
  File "/home/spaceone/git/circuits/circuits/core/manager.py", line 681, in _dispatcher
    value = event_handler(*eargs, **ekwargs)
  File "/home/spaceone/git/circuits/circuits/net/sockets.py", line 588, in _on_read
    self._accept()
  File "/home/spaceone/git/circuits/circuits/net/sockets.py", line 538, in _accept
    _do_handshake_for_non_blocking(sslsock)
  File "/home/spaceone/git/circuits/circuits/net/sockets.py", line 208, in _do_handshake_for_non_blocking
    ssock.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
AttributeError: 'NoneType' object has no attribute 'do_handshake'
```

**Comment by spaceone** [comment]
What is pending here?

**Comment by prologic** [comment]
The current solution doesn't quite work I don't think. Needs work :/


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by spaceone** [comment]
If you provide a reproducal-example I will have a look.

**Comment by spaceone** [comment]
@prologic Please describe properly what is still open/necessary/not working here.

**Comment by prologic** [comment]
Closing this as stale.
