### ISSUE TITLE
recursion error if handshake fails

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#115]
The following code:
```
from circuits.net.sockets import TCPClient
from circuits.net.events import connect, write
from circuits import Debugger

s = TCPClient(channel='www')
s.fire(connect('master10.local.dev', 443, True))
s += Debugger(events=True)
s.run()
```

produces:
```
<connect[www] ('master10.local.dev', 443, True )>
<registered[*] (<Debugger/* 5801:MainThread (queued=0) [S]>, <TCPClient/www 5801:MainThread (queued=2) [R]> )>
<started[www] (<TCPClient/www 5801:MainThread (queued=1) [R]> )>
<registered[select] (<Select/select 5801:MainThread (queued=0) [S]>, <TCPClient/www 5801:MainThread (queued=3) [R]> )>
<ready[www] (<TCPClient/www 5801:MainThread (queued=2) [R]> )>
<exception[www] (<class 'ssl.SSLError'>, SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)'), ['  File "/home//git/circuits/circuits/core/manager.py", line 844, in processTask\n    value = next(task)\n', '  File "/home//git/circuits/circuits/net/sockets.py", line 283, in connect\n    _do_handshake_for_non_blocking(self._sock)\n', '  File "/home//git/circuits/circuits/net/sockets.py", line 210, in _do_handshake_for_non_blocking\n    ssock.do_handshake()\n', '  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake\n    self._sslobj.do_handshake()\n'] handler=None, fevent=<connect[www] ('master10.local.dev', 443, True )>)>
ERROR  (<connect[www] ('master10.local.dev', 443, True )>) (<class 'ssl.SSLError'>): SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)')
Traceback (most recent call last):
  File "/home//git/circuits/circuits/core/manager.py", line 844, in processTask
    value = next(task)
  File "/home//git/circuits/circuits/net/sockets.py", line 283, in connect
    _do_handshake_for_non_blocking(self._sock)
  File "/home//git/circuits/circuits/net/sockets.py", line 210, in _do_handshake_for_non_blocking
    ssock.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)

<_read[www] (<socket._socketobject object at 0x7f8cdb9c2830> )>
<error[www] (error(9, 'Bad file descriptor') )>
<_read[www] (<socket._socketobject object at 0x7f84838b0830> )>
<error[www] (error(9, 'Bad file descriptor') )>
<_read[www] (<socket._socketobject object at 0x7f84838b0830> )>
<error[www] (error(9, 'Bad file descriptor') )>
… [never ending]
```

**Comment by spaceone** [comment]
The error handling should be adapted. It should stop with only 1 error event.

**Comment by prologic** [comment]
I agree; let's fix this :+1:

**Comment by prologic** [comment]
Closing in favour of #114

**Comment by spaceone** [comment]
Thanks, no recursion anymore.

**Comment by prologic** [comment]
With the [fix_ssl_handshake#114](https://github.com/circuits/circuits/tree/fix_ssl_handshake%23114) branch?

**Comment by spaceone** [comment]
yep

**Comment by prologic** [comment]
Oh beautiful :) I made the *right* call then :P

**Comment by spaceone** [comment]
The error handling is still incomplete. The exception should not occur after the error event.
```
<connect[www] ('master10.local.dev', 443, True )>
<registered[*] (<Debugger/* 13779:MainThread (queued=0) [S]>, <TCPClient/www 13779:MainThread (queued=2) [R]> )>
<started[www] (<TCPClient/www 13779:MainThread (queued=1) [R]> )>
<registered[select] (<Select/select 13779:MainThread (queued=0) [S]>, <TCPClient/www 13779:MainThread (queued=2) [R]> )>
<ready[www] (<TCPClient/www 13779:MainThread (queued=1) [R]> )>
<error[www] (<ssl.SSLSocket object at 0x7f239088ede8>, SSLError(1, u'[SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:581)') )>
<disconnected[www] ( )>
<exception[www] (<class 'socket.error'>, error(9, 'Bad file descriptor'), ['  File "/home//git/circuits/circuits/core/manager.py", line 844, in processTask\n    value = next(task)\n', '  File "/home//git/circuits/circuits/net/sockets.py", line 299, in connect\n    for _ in do_handshake(self._sock, on_done, on_error):\n', '  File "/home//git/circuits/circuits/net/sockets.py", line 61, in do_handshake\n    sock.do_handshake()\n', '  File "/usr/lib/python2.7/ssl.py", line 784, in do_handshake\n    timeout = self.gettimeout()\n', '  File "/usr/lib/python2.7/socket.py", line 224, in meth\n    return getattr(self._sock,name)(*args)\n', '  File "/usr/lib/python2.7/socket.py", line 170, in _dummy\n    raise error(EBADF, \'Bad file descriptor\')\n'] handler=None, fevent=<connect[www] ('master10.local.dev', 443, True )>)>
ERROR  (<connect[www] ('master10.local.dev', 443, True )>) (<class 'socket.error'>): error(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/home//git/circuits/circuits/core/manager.py", line 844, in processTask
    value = next(task)
  File "/home//git/circuits/circuits/net/sockets.py", line 299, in connect
    for _ in do_handshake(self._sock, on_done, on_error):
  File "/home//git/circuits/circuits/net/sockets.py", line 61, in do_handshake
    sock.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 784, in do_handshake
    timeout = self.gettimeout()
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
```

**Comment by prologic** [comment]
But ``exception()`` is an "unhandled exception" whilst ``error()`` is a "socket error"?

**Comment by spaceone** [comment]
yes, but the exception should not occur at all. If the error() event is send at that point no further processing (like polling, etc.) should be done.

**Comment by prologic** [comment]
I agree; there must be a ``raise`` (*reraising the exception*) after the ``error()`` event is fired :) PR welcome!

**Comment by spaceone** [comment]
OK, here: https://github.com/circuits/circuits/pull/122

**Comment by prologic** [comment]
:+1:
