### ISSUE TITLE
WebSocket read events should carry the session information

### ISSUE THREAD

**Issue by mnlipp** [circuits/circuits#132]
While continuing work on my circuits based portal, I found a problem with the "read" event from a web socket: it doesn't carry the session information as "ordinary" requests from http clients do.

I have a timeline to meet and cannot develop against 3.2-dev currently. So here's my work-around for 3.1, which can easily be merged with the WebSocketDispatcher.

```python
from circuits.web.websockets.dispatcher import WebSocketsDispatcher
from circuits.core.handlers import handler

class WebSocketsDispatcherPlus(WebSocketsDispatcher):

    def __init__(self, path=None, wschannel="wsserver", *args, **kwargs):
        super(WebSocketsDispatcherPlus, self).__init__ \
            (path, wschannel, *args, **kwargs)
        self._sessions = dict()
        @handler("read", channel=wschannel, priority=100)
        def _on_read_handler(self, event, socket, data):
            if socket in self._sessions:
                event.kwargs["session"] = self._sessions[socket]
        self.addHandler(_on_read_handler)
        
    @handler("response_complete")
    def _on_response_complete(self, e, value):
        response = e.args[0]
        request = response.request
        if request.sock in self._codecs:
            self._sessions[request.sock] = request.session

    @handler("disconnect")
    def _on_disconnect(self, sock):
        if sock in self._sessions:
            del self._sessions[sock]
```

**Comment by mnlipp** [comment]
I just noticed that I need the session when handling "connect" and "disconnect" as well. So this becomes:

```python
from circuits.web.websockets.dispatcher import WebSocketsDispatcher
from circuits.core.handlers import handler
from circuits.net.events import connect, disconnect

class WebSocketsDispatcherPlus(WebSocketsDispatcher):
    def __init__(self, path=None, wschannel="wsserver", *args, **kwargs):
        super(WebSocketsDispatcherPlus, self).__init__ \
            (path, wschannel, *args, **kwargs)
        self._sessions = dict()
        @handler("read", channel=wschannel, priority=100)
        def _on_read_handler(self, event, socket, data):
            if socket in self._sessions:
                event.kwargs["session"] = self._sessions[socket]
        self.addHandler(_on_read_handler)

    @handler("response_complete", override=True)
    def _on_response_complete(self, e, value):
        response = e.args[0]
        request = response.request
        if request.sock in self._codecs:
            self._sessions[request.sock] = request.session
        if request.sock in self._codecs:
            evt = connect(request.sock,*request.sock.getpeername())
            evt.kwargs["session"] = request.session 
            self.fire(evt, self._wschannel)
        
    @handler("disconnect", override=True)
    def _on_disconnect(self, sock):
        if sock in self._codecs:
            evt = disconnect(sock)
            if sock in self._sessions:
                evt.kwargs["session"] = self._sessions[sock] 
                del self._sessions[sock]
            self.fire(evt, self._wschannel)
            del self._codecs[sock]
```

(Easier to merge, anyway)

**Comment by prologic** [comment]
Cool! Thanks. If you throw this into a new GH Issue; we'll try to get it
merged before the upcoming 3.2

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by mnlipp** [comment]
I'm confused: "If you throw this into a new GH Issue..." -- isn't this a GH issue already? Why a new one?

**Comment by prologic** [comment]
Ooops :) So sorry; I didn't notice this thread was a GH Issue! My bad!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by spaceone** [comment]
@mnlipp do you still need this?
I have a pull request to fix it.

Question: we are giving the session there now. We could instead also give the request and you can access the session via `request.session`. I am unsure if this leaks memory, because the request is cleaned up only on disconnecting then.

**Comment by mnlipp** [comment]
> @mnlipp do you still need this?
> I have a pull request to fix it.

I'm still using the workaround, so yes.

> Question: we are giving the session there now. We could instead also give the request and you can access the session via `request.session`. I am unsure if this leaks memory, because the request is cleaned up only on disconnecting then.

I'm not sure what you mean by "request". The point is that when I receive events from the websocket, I need "context", i.e. the session from which the websocket was (or is being) opened. So the crucial code is
```python
@handler("read", channel=wschannel, priority=100)
        def _on_read_handler(self, event, socket, data):
            if socket in self._sessions:
                event.kwargs["session"] = self._sessions[socket]
```
(and setting `event.kwargs["session"]` for connect and disconnect events). Everything else just makes this work by managing `self._sessions`.

**Comment by spaceone** [comment]
@mnlipp In my PR you would have a `event.kwargs['request'].session` - or as adding a new kwarg is a breaking API change, I might add it to the event as `event.request.session`.

How did you manage that your event handlers are working? Did you add a session keyword argument?

**Comment by spaceone** [comment]
```
Traceback (most recent call last):
  File "/home/runner/work/circuits/circuits/circuits/core/manager.py", line 679, in _dispatcher
    value = event_handler(*eargs, **ekwargs)
TypeError: connect() got an unexpected keyword argument 'request'
```


```
Traceback (most recent call last):
  File "/home/runner/work/circuits/circuits/circuits/core/manager.py", line 679, in _dispatcher
    value = event_handler(*eargs, **ekwargs)
TypeError: disconnect() got an unexpected keyword argument 'request'
```

**Comment by spaceone** [comment]
@mnlipp The PR now passes the tests.
The differences for you would be:

instead of:
`def connect(self, sock, session):`

you do:
```
def connect(self, event, sock):
    session = event.request.session
```

Would this be okay for you?

**Comment by mnlipp** [comment]
How about the read event? How can I access the session when I receive data from the web socket? (As shown above, my workaround added the session as kwarg to the read event.) There is no "request" associated with a read event.

**Comment by mnlipp** [comment]
> How did you manage that your event handlers are working? Did you add a session keyword argument?

Yes. Why provide the information, if it isn't used? But of course, this *is* a breaking change for everybody not expecting it. (Actually, I use a final **kwargs or *args on all my handlers, as I have always been to lazy to lookup what I --might-- get as arguments in addition to what I need.)

**Comment by spaceone** [comment]
> How about the read event? How can I access the session when I receive data from the web socket? (As shown above, my workaround added the session as kwarg to the read event.) There is no "request" associated with a read event.
The same as the comment above. If you add a first argument `event` you can access it via `event.request.session`.

**Comment by spaceone** [comment]
> > How did you manage that your event handlers are working? Did you add a session keyword argument?
> 
> Yes. Why provide the information, if it isn't used? But of course, this _is_ a breaking change for everybody not expecting it. (Actually, I use a final **kwargs or *args on all my handlers, as I have always been to lazy to lookup what I --might-- get as arguments in addition to what I need.)

We can't do this breaking change, therefor I added the information directly into the event.
The current handlers showed that they all fail because they don't accept keyword arguments.

**Comment by mnlipp** [comment]
> > How about the read event? How can I access the session when I receive data from the web socket? (As shown above, my workaround added the session as kwarg to the read event.) There is no "request" associated with a read event.
> 
> The same as the comment above. If you add a first argument `event` you can access it via `event.request.session`.

Okay, I suppose this will work. I'm still wondering what kind of information there is in `event.request` (besides the `session`), because the browser does *not* send requests on web sockets when it sends data (only the initial connection establishment is a request). But as long as I can access the session, everything is fine for me.

**Comment by spaceone** [comment]
@mnlipp sorry for the delayed answer, I thought I already replied.

yes, in websockets there is of course only a initial HTTP request to establish the connection. That request would be passed along with e.g. the read events, where you can get the session from. Of course this request is old and already answered. And maybe it's useful for further things, e.g. if one wants to evaluate some additional headers like `Accept-Language`. 

I am going to merge this soon, then and do a new circuits release.

**Comment by spaceone** [comment]
@mnlipp `circuits 3.2.2` has been released, including the fix :-)
