### ISSUE TITLE
[MicroPython+WiPy]: Lack of inspect module

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#16]
The lack of the ``inspect`` module is going to cause a lot of issues:

```#!python
prologic@daisy
Mon Apr 27 08:49:42 
~/circuits
$ micropython 
Micro Python  on 2015-04-27; linux version
>>> import circuits
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "circuits/__init__.py", line 22, in <module>
  File "circuits/core/__init__.py", line 11, in <module>
  File "circuits/core/events.py", line 11, in <module>
ImportError: no module named 'inspect'
```

See: micropython/micropython-lib#22

**Comment by prologic** [comment]
This initial error can be fixed with:

```#!diff
diff --git a/circuits/core/events.py b/circuits/core/events.py
index 1cb2947..62d3e4a 100644
--- a/circuits/core/events.py
+++ b/circuits/core/events.py
@@ -8,7 +8,7 @@ This module defines the basic event class and common events.
 """
 
 
-from inspect import ismethod
+from types import MethodType
 
 
 class EventType(type):
@@ -352,7 +352,7 @@ class generate_events(Event):
                         ),
                         "resume", None
                     )
-                    if m is not None and ismethod(m):
+                    if m is not None and type(m) is MethodType:
                         m()
 
     @property
```

However there are going to be many more instances of this that will need to be fixed or ported in some other way.

**Comment by prologic** [comment]
Also I think if we're going to "port" anything we should keep circuits compatible with CPython as well as MicroPython

**Comment by prologic** [comment]
See: micropython/micropython#405
