### ISSUE TITLE
Parsing remote host headers for UNIX bound web server

### ISSUE THREAD

**Issue by prologic** [circuits/circuits#162]
While trying to develop a Docker Volume Driver Plugin and binding a circuits.web.Server to a UNIX Socket I noticed:

```#!python
nfsvolumedriver_1  | <connect[web] (<socket._socketobject object at 0x7f605e50f8a0> )>
nfsvolumedriver_1  | <_read[web] (<socket._socketobject object at 0x7f605e50f8a0> )>
nfsvolumedriver_1  | <read[web] (<socket._socketobject object at 0x7f605e50f8a0>, 'POST /Plugin.Activate HTTP/1.1\r\nHost: \r\nUser-Agent: Go-http-client/1.1\r\nContent-Length: 0\r\nAccept: application/vnd.docker.plugins.v1.2+json\r\n\r\n' )>
nfsvolumedriver_1  | <exception[*] (<type 'exceptions.TypeError'>, TypeError('__init__() takes at least 3 arguments (1 given)',), ['  File "/usr/lib/python2.7/site-packages/circuits/core/manager.py", line 661, in _dispatcher\n    value = event_handler(*eargs, **ekwargs)\n', '  File "/usr/lib/python2.7/site-packages/circuits/web/http.py", line 270, in _on_read\n    headers=parser.get_headers(), server=self._server\n', '  File "/usr/lib/python2.7/site-packages/circuits/web/wrappers.py", line 180, in __init__\n    self.remote = Host(*name)\n'] handler=<bound method HTTP._on_read of <HTTP/web 1:MainThread (queued=0) [S]>>, fevent=<read[web] (<socket._socketobject object at 0x7f605e50f8a0>, 'POST /Plugin.Activate HTTP/1.1\r\nHost: \r\nUser-Agent: Go-http-client/1.1\r\nContent-Length: 0\r\nAccept: application/vnd.docker.plugins.v1.2+json\r\n\r\n' )>)>
nfsvolumedriver_1  | ERROR <handler[*][read] (HTTP._on_read)> (<read[web] (<socket._socketobject object at 0x7f605e50f8a0>, 'POST /Plugin.Activate HTTP/1.1\r\nHost: \r\nUser-Agent: Go-http-client/1.1\r\nContent-Length: 0\r\nAccept: application/vnd.docker.plugins.v1.2+json\r\n\r\n' )>) (<type 'exceptions.TypeError'>): TypeError('__init__() takes at least 3 arguments (1 given)',)
nfsvolumedriver_1  | Traceback (most recent call last):
nfsvolumedriver_1  |   File "/usr/lib/python2.7/site-packages/circuits/core/manager.py", line 661, in _dispatcher
nfsvolumedriver_1  |     value = event_handler(*eargs, **ekwargs)
nfsvolumedriver_1  |   File "/usr/lib/python2.7/site-packages/circuits/web/http.py", line 270, in _on_read
nfsvolumedriver_1  |     headers=parser.get_headers(), server=self._server
nfsvolumedriver_1  |   File "/usr/lib/python2.7/site-packages/circuits/web/wrappers.py", line 180, in __init__
nfsvolumedriver_1  |     self.remote = Host(*name)
nfsvolumedriver_1  | TypeError: __init__() takes at least 3 arguments (1 given)
```

**Comment by prologic** [comment]
@spaceone or @justingiorgi would either of you care to have a look at this? :)

**Comment by spaceone** [comment]
```
diff --git a/circuits/web/wrappers.py b/circuits/web/wrappers.py
index 38ccbff..2751347 100644
--- a/circuits/web/wrappers.py
+++ b/circuits/web/wrappers.py
@@ -179,3 +179,8 @@ class Request(object):
             if name is not None:
-                self.remote = Host(*name)
+                try:
+                       ip, port = name
+                       name = None
+                except ValueError:  # AF_UNIX
+                       ip, port = None, None
+                self.remote = Host(ip, port, name)
             else:
```

**Comment by prologic** [comment]
Probably better to do it this way too; don't have to stat the file system :)

**Comment by prologic** [comment]
Amended :)
