### ISSUE TITLE
multiprocessing broken in Windows

### ISSUE THREAD

**Issue by guruofgentoo** [circuits/circuits#199]
### Expected Behaviour

I am attempting to run the multiprocessing-related examples (ping-pong specifically for this issue, but output is similar for hello_bridge and hello_multi_bridge) in Windows. The example should start a child process, and then be able to fire events bidirectionally.

### Steps to reproduce

In Windows, create a virtual environment and install circuits (and only circuits). Modify the ping-pong example to have
```
if __name__ == '__main__':
    App().run()
```
for its main code (instead of the existing `App().run()`). Then run `python pingpong.py`.

Output for 2.7:
```
Traceback (most recent call last):
  File "circuits_example.py", line 77, in <module>
    App().run()
  File "C:\work\python\tempstage2\lib\site-packages\circuits\core\components.py", line 123, in __init__
    self.init(*args, **kwargs)
  File "circuits_example.py", line 52, in init
    Child().start(process=True, link=self)
  File "C:\work\python\tempstage2\lib\site-packages\circuits\core\manager.py", line 752, in start
    parent, child = Pipe(*channels)
  File "C:\work\python\tempstage2\lib\site-packages\circuits\net\sockets.py", line 837, in Pipe
    from socket import socketpair
ImportError: cannot import name socketpair
```

Output for 3.5:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\python35\Lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "c:\python\python35\Lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
AttributeError: 'Child' object has no attribute '_on_prepare_unregister_complete'
```

Output for 3.6:
```
Traceback (most recent call last):
  File "circuits_example.py", line 77, in <module>
    App().run()
  File "C:\work\python\tempstage\lib\site-packages\circuits\core\components.py", line 123, in __init__
    self.init(*args, **kwargs)
  File "circuits_example.py", line 52, in init
    Child().start(process=True, link=self)
  File "C:\work\python\tempstage\lib\site-packages\circuits\core\manager.py", line 764, in start
    self.__process.start()
  File "c:\python\python36\Lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "c:\python\python36\Lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\python\python36\Lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\python\python36\Lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\python\python36\Lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _thread.RLock objects

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python\python36\Lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "c:\python\python36\Lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect
```

### Environment and Platform

- OS: Windows
- Python: 2.7, 3.5, 3.6
- circuits: 3.2

----

**Comment by prologic** [comment]
Hmm at first glance this loos like a bug in circuits **and** missing
feature for Windows.

Specifically there is no "pipe" or "uni socket" in Windows :/

The only way to make the Pipe() component work in Windows is to detect that
we're in a windows environment and fake the pipe by creating a
server<->client socket connection.

Do you have enough Windows and programming background to have a crack at
this?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
**Note:** None of the active developers here have access to a Windows machine to test a fix for this. Any fix for this will require someone with access to a Windows machine. As stated, "Windows support" is a "best effort".

**Comment by jvickroy** [comment]
> As stated, "Windows support" is a "best effort".

In that case, I would like to request the FAQ be corrected.

From [http://circuits.readthedocs.io/en/latest/faq.html](url)

> ... What platforms does circuits support?
    circuits currently supports Linux, FreeBSD, OSX and Windows and is currently continually tested against Linux and Windows against Python versions 2.7, 3.4, 3.5 and 3.6

**Comment by prologic** [comment]
Can you submit a PR? :D


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
