### ISSUE TITLE
echoserial.py example not running on windows

### ISSUE THREAD

**Issue by niecore** [circuits/circuits#237]
The `echoserial.py`  does not run on windows machines.

`<registered[serial] (<Serial/serial 8708:MainThread (queued=0) [S]>, <EchoSerial/* 8708:MainThread (queued=3) [R]> )>
<registered[*] (<Debugger/* 8708:MainThread (queued=0) [S]>, <EchoSerial/* 8708:MainThread (queued=4) [R]> )>
<started[*] (<EchoSerial/* 8708:MainThread (queued=3) [R]> )>
<registered[select] (<Select/select 8708:MainThread (queued=0) [S]>, <Serial/serial 8708:MainThread (queued=0) [S]> )>
<ready[serial] (<Serial/serial 8708:MainThread (queued=0) [S]> )>
<_open[serial] ( )>
<exception[*] (<class 'io.UnsupportedOperation'>, UnsupportedOperation('fileno',), ['  File "C:\\Program Files\\Anaconda3\\lib\\site-packages\\circuits\\core\\manager.py", line 661, in _dispatcher\n    value = event_handler(*eargs, **ekwargs)\n', '  File "C:\\Program Files\\Anaconda3\\lib\\site-packages\\circuits\\io\\serial.py", line 59, in _on_open\n    self._fd = self._serial.fileno()  # not portable!\n'] handler=<bound method Serial._on_open of <Serial/serial 8708:MainThread (queued=0) [S]>>, fevent=<_open[serial] ( )>)>
ERROR <handler[*][_open] (Serial._on_open)> (<_open[serial] ( )>) (<class 'io.UnsupportedOperation'>): UnsupportedOperation('fileno',)
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\circuits\core\manager.py", line 661, in _dispatcher
    value = event_handler(*eargs, **ekwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\circuits\io\serial.py", line 59, in _on_open
    self._fd = self._serial.fileno()  # not portable!
io.UnsupportedOperation: fileno

`

### Environment and Platform

- OS: windows 7
- Python: 3.6
- circuits: 3.3

----

**Comment by spaceone** [comment]
select on Windows does not work with files or serial ports, only sockets.
I don't have a windows system available and have no idea what I could do to fix it.
