### ISSUE TITLE
- and -= syntax broken

### ISSUE THREAD

**Issue by spaceone** [circuits/circuits#93]
```
>>> from circuits import *
>>> a = BaseComponent(channel='a')
>>> b = BaseComponent(channel='b')
>>> a + b
<BaseComponent/a 13837:MainThread (queued=1) [S]>
>>> a - b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fbest/git/circuits/circuits/core/manager.py", line 288, in __sub__
    if y.manager is not y:
AttributeError: 'BaseComponent' object has no attribute 'manager'
>>> a -= b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fbest/git/circuits/circuits/core/manager.py", line 302, in __isub__
    if y.manager is not y:
AttributeError: 'BaseComponent' object has no attribute 'manager'
>>> 

```

**Comment by prologic** [comment]
As discussed on [#circuits](http://irclogs.shortcircuit.net.au/%23circuits/latest.log.html#t02:12:02) let's:

* [ ] Identify the change
* [ ] Fix the bug due to the above change

I recall some of the internals changed such that we now have ``.root`` and ``.parent``.

**Comment by prologic** [comment]
Found the commit:  9eb346df79

**Comment by prologic** [comment]
Now let's fix this :)
